import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [state, setState] = React.useState(0);
  const handleClick = () => {
    setState(prev => prev + 1);
  }

  useEffect(() => {
    console.log("count: ", state);
    if (state === 5) {
      throw Error("error")
    }
  }, [state]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleClick}>click</button>
    </div>
  )
}
